# Generated by Django 4.2 on 2023-05-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('JobTitle', models.CharField(max_length=100)),
                ('JobDescription', models.CharField(max_length=1000)),
                ('JobLocation', models.CharField(max_length=100)),
                ('JobType', models.CharField(max_length=100)),
                ('JobCategory', models.CharField(max_length=100)),
                ('JobSalary', models.CharField(max_length=100)),
            ],
        ),
    ]
