# Generated by Django 4.2 on 2023-05-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_users_id_alter_users_user_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
