# Generated by Django 4.2 on 2023-05-08 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0005_alter_users_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Id',
        ),
        migrations.AlterField(
            model_name='users',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
