# Generated by Django 4.2 on 2023-05-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_users_id_alter_users_user_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Country',
            field=models.CharField(default='India', max_length=100),
            preserve_default=False,
        ),
    ]
