# Generated by Django 4.2 on 2023-05-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_users_profilephoto_alter_users_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='ProfilePhoto',
            field=models.ImageField(default='ProfilePhoto/default.png', null=True, upload_to='ProfilePhoto'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Resume',
            field=models.FileField(default='Resume/default.pdf', null=True, upload_to='Resume'),
        ),
    ]
