# Generated by Django 4.2 on 2023-05-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_users_profilephoto_alter_users_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='peopleApplied',
            field=models.ManyToManyField(blank=True, related_name='peopleApplied', to='Home.users'),
        ),
    ]
