# Generated by Django 4.2 on 2023-05-12 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_remove_jobs_peopleapplied_jobs_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='Apply',
        ),
        migrations.CreateModel(
            name='applecant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.users')),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='applecant',
            field=models.ManyToManyField(blank=True, related_name='applecant', to='Home.applecant'),
        ),
    ]
