# Generated by Django 4.2 on 2023-05-12 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0013_remove_jobs_apply_applecant_jobs_applecant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='applecant',
        ),
        migrations.AddField(
            model_name='jobs',
            name='People_applyed',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
