# Generated by Django 4.2 on 2023-05-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_jobs_people_applyed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='People_applyed',
        ),
        migrations.AddField(
            model_name='jobs',
            name='SubmitedByResumas',
            field=models.FileField(default='Resumes/default.pdf', null=True, upload_to='Resumes'),
        ),
    ]
