# Generated by Django 4.2 on 2023-05-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_remove_jobs_people_applyed_jobs_submitedbyresumas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='applecant',
        ),
    ]
