# Generated by Django 4.2 on 2023-05-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_delete_applecant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='SubmitedByResumas',
        ),
        migrations.AddField(
            model_name='jobs',
            name='SubmitedByResumas',
            field=models.ManyToManyField(blank=True, related_name='SubmitedByResumas', to='Home.users'),
        ),
    ]
